### ISSUE TITLE
Node API - ReferenceError: window is not defined

### ISSUE THREAD

**Issue by csmith14** [scriptex/svg64#88]
Package, version 0.1.0, added via `yarn add -D svg64`

Calling the method exposed by `require('svg64').default` throws a `ReferenceError` due to webpack implementation.

stdout:
```shell
%PROJECT%\node_modules\svg64\dist\svg64.js:10
})(window, function() {
   ^

ReferenceError: window is not defined
```

package.json:
```json
"devDependencies": {
	"svg64": "^0.1.0"
}
```

Usage in script:
```js
// Required
const SVG64 = require( 'svg64' ).default
/* ... */
// Called
const data = SVG64( readFileSync( input, 'utf-8' ) )
```

**Comment by scriptex** [comment]
Hello and thanks for finding this issue!
I have reimplemented the whole package.
It now has zero dependencies and should work a bit better :)
Please refer to the [README](https://github.com/scriptex/svg64#usage) for more info about the usage.
If you want to take a quick look in the changes: see 1e088f852a179ff8249ebd41df30dd67930c70e7
The new version is released under 1.0.0 tag and is available on NPM too.
Let me know if I missed something!
Thanks once again!
